name: CI

on:
  workflow_dispatch:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    #runs-on: windows-2022
    runs-on: windows-2019
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Build ImDisk x64 Isolator
        run: msbuild /t:build ImDisk.sln /p:Configuration="Release" /p:Platform=x64
        
      - name: Build ImDisk ARM64 Isolator
        run: msbuild /t:build ImDisk.sln /p:Configuration="Release" /p:Platform=ARM64

      - name: Build ImDisk i386 Isolator
        run: msbuild /t:build ImDisk.sln /p:Configuration="Release" /p:Platform=win32

      - name: Upload Build 
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ImDisk
          path: |
            Release/*/*/*.exe
            Release/*/*/*.cpl
            Release/*/*/*.dll
            Release/*/*/*.sys
            Release/*/*/*.pdb
